version: '1'
services:
  app:
    build: .
    ports:
      - "5002:5002"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/Ecommerce
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: